### ISSUE TITLE
Create search bar and filter button: ViewModel + Query the database interface + test

### ISSUE THREAD

**Issue by nikhen-s** [swent-sp-2024-event-radar/event-radar-app#117]
## Link to User Stories
#15, #16, In Figma user flows 3, 4

## Objective
Create ViewModel for Search Bar and Filter Button. 

## Acceptance Criteria
- [ ]

**Comment by christinehahaa** [comment]
15hours were spent on this task in sprint 6 to try get it merged by M2. Unfortunately, VM tests were not passing and there were several nasty bugs, so it couldn't be merged in by then. 

The VM tests were finished and bugs fixed in Sprint 7. Then the PR reviewed at the end of Sprint 7. The review required a lot of changes, so it wasn't merged until Monday of Sprint 8.
