### ISSUE TITLE
Implement Google Authentication For Landing Page

### ISSUE THREAD

**Issue by jgeaso1266** [swent-sp-2024-event-radar/event-radar-app#4]
# Link to User Stories
#13, User flow 2 in Figma

# Objective
- Implement Google Authentication for users to be able to view and modify required information to use the app
- Link it to the Firebase User database (#14)

# Acceptance Criteria
- [ ] Button on landing page calls the Google Authentication API
- [ ] Upon successful authentication, navigate to home page
- [ ] Upon failing authentication, navigate back to login page (and show error message)

**Comment by achillet3** [comment]
# Link to User Stories
#12 and #13
# Objective
- Implement Google Authentification for users to be able to create an account and save required information to use the app
- Link it to the firebase User database 
# Required behaviour
- User information should be stored so that they can log in from different devices and stay logged in
